//! Embeds the admin interface, and records how stale it is.
//!
//! # The problem this solves
//!
//! Cargo does not know the front end exists. A release build bakes in whatever
//! was in `frontend/admin/dist/` at compile time, and **nothing re-runs the
//! front-end build when its sources change** — so a binary can easily carry an
//! interface nobody is looking at any more, and the only symptom is a UI that
//! does not match the code.
//!
//! Two things make that visible:
//!
//! * This script walks the bundle and records the newest modification time it
//!   saw, as a constant the crate can report. Comparing it against the front-end
//!   sources is what a staleness warning is built from.
//! * When the bundle is absent, an empty bundle is recorded rather than a build
//!   failure. A backend-only checkout has no `node_modules`, and a developer
//!   working on the agent must not be blocked by that.
//!
//! # Why the file list is generated rather than globbed at compile time
//!
//! `include_dir!` would be simpler, but it cannot tell the crate *which* files it
//! embedded or when they were last written — and knowing that is the whole point
//! of this script.

use std::path::{Path, PathBuf};
use std::time::SystemTime;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../../frontend/admin/dist");

    let root = Path::new("../../frontend/admin/dist");
    let entries = collect(root);

    let generated = match entries {
        Some(entries) if !entries.is_empty() => {
            let newest = entries.iter().filter_map(|(_, modified)| *modified).max();
            let mut source = String::from(
                "// @generated by build.rs — the admin interface bundle.\n\
                 /// The embedded interface files, as request paths.\n\
                 pub const BUNDLE: Option<&[(&str, &[u8])]> = Some(&[\n",
            );
            for (path, _) in &entries {
                // The absolute path is used for the `include_bytes!` call, because
                // the macro resolves relative to the file that contains it.
                let absolute = std::fs::canonicalize(root.join(path.trim_start_matches('/')))
                    .unwrap_or_else(|_| root.join(path.trim_start_matches('/')));
                source.push_str(&format!(
                    "    ({:?}, include_bytes!({:?})),\n",
                    path,
                    absolute.display().to_string()
                ));
            }
            source.push_str("]);\n");
            source.push_str(&format!(
                "/// The newest modification time in the bundle, in Unix seconds.\n\
                 pub const BUNDLE_MODIFIED: Option<u64> = Some({});\n",
                newest
                    .and_then(|t| t.duration_since(SystemTime::UNIX_EPOCH).ok())
                    .map(|d| d.as_secs())
                    .unwrap_or(0)
            ));
            source
        }
        _ => {
            println!(
                "cargo:warning=frontend/admin/dist is missing or empty; the admin interface \
                 will serve a placeholder page. Run `pnpm --dir frontend/admin build` first \
                 for a real one."
            );
            "// @generated by build.rs — no bundle was found.\n\
             /// The embedded interface files, absent when the front end was not built.\n\
             pub const BUNDLE: Option<&[(&str, &[u8])]> = None;\n\
             /// The newest modification time in the bundle, when there is one.\n\
             pub const BUNDLE_MODIFIED: Option<u64> = None;\n"
                .to_owned()
        }
    };

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("assets_bundle.rs");
    std::fs::write(&out, generated).expect("cannot write the generated bundle");
}

/// Walks `root`, returning every file as a request path with its modification time.
fn collect(root: &Path) -> Option<Vec<(String, Option<SystemTime>)>> {
    if !root.is_dir() {
        return None;
    }
    let mut out = Vec::new();
    walk(root, root, &mut out);
    Some(out)
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, Option<SystemTime>)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, out);
        } else {
            let Ok(relative) = path.strip_prefix(root) else {
                continue;
            };
            let request_path = format!("/{}", relative.display());
            let modified = entry.metadata().ok().and_then(|m| m.modified().ok());
            out.push((request_path, modified));
        }
    }
    // A stable order, so the generated file does not churn between builds and
    // invalidate the crate's own compilation for no reason.
    out.sort_by(|a, b| a.0.cmp(&b.0));
}
