//! Embeds the two browser interfaces, and records how stale they are.
//!
//! # The problem this solves
//!
//! Cargo does not know either front end exists. A release build bakes in whatever
//! was in `frontend/admin/dist/` and `frontend/metacubexd/dist/` at compile time,
//! and **nothing re-runs either build when its sources change** — so a binary can
//! easily carry an interface nobody is looking at any more, and the only symptom
//! is a UI that does not match the code.
//!
//! Two things make that visible:
//!
//! * This script walks each bundle and records the newest modification time it
//!   saw, as a constant the crate can report. Comparing it against the front-end
//!   sources is what a staleness warning is built from.
//! * When a bundle is absent, an empty bundle is recorded rather than a build
//!   failure. A backend-only checkout has no `node_modules`, and a developer
//!   working on the agent must not be blocked by that — nor by the dashboard
//!   fetch, which needs the network.
//!
//! # Why the file list is generated rather than globbed at compile time
//!
//! `include_dir!` would be simpler, but it cannot tell the crate *which* files it
//! embedded or when they were last written — and knowing that is the whole point
//! of this script.
//!
//! # Why both bundles come from one function
//!
//! The admin interface and the dashboard are embedded in the same shape for
//! different reasons, and the handling above is identical for both. Two copies of
//! it would drift — most likely in the absent-bundle path, which is the one that
//! only runs on a developer's machine.

use std::path::{Path, PathBuf};
use std::time::SystemTime;

/// One embedded bundle's inputs and outputs.
struct Bundle {
    /// The directory to walk, relative to this crate.
    root: &'static str,
    /// The prefix this bundle is served under, as a request path.
    ///
    /// Stored alongside the file so a route can be checked against the bundle it
    /// came from without repeating the prefix, which is the kind of constant that
    /// silently disagrees when one site is changed.
    prefix: &'static str,
    /// The generated constant naming this bundle.
    name: &'static str,
    /// What to tell a developer when the bundle is missing.
    hint: &'static str,
}

const BUNDLES: &[Bundle] = &[
    Bundle {
        root: "../../frontend/admin/dist",
        prefix: "",
        name: "ADMIN",
        hint: "run `pnpm --dir frontend/admin build`",
    },
    Bundle {
        root: "../../frontend/metacubexd/dist",
        prefix: "/ui",
        name: "METACUBEXD",
        hint: "run `scripts/fetch-metacubexd.sh`",
    },
];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let mut generated = String::from(
        "// @generated by build.rs — the embedded browser interfaces.\n\
         //\n\
         // Each bundle records the files it contains, the prefix it is served\n\
         // under, and the newest modification time it saw.\n",
    );

    for bundle in BUNDLES {
        println!("cargo:rerun-if-changed={}", bundle.root);
        generated.push_str(&render(bundle));
    }

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("assets_bundle.rs");
    std::fs::write(&out, generated).expect("cannot write the generated bundle");
}

/// Renders the constants for one bundle.
fn render(bundle: &Bundle) -> String {
    let root = Path::new(bundle.root);
    let entries = collect(root);
    let name = bundle.name;
    let prefix = bundle.prefix;

    let Some(entries) = entries.filter(|entries| !entries.is_empty()) else {
        println!(
            "cargo:warning={} is missing or empty; {} will serve a placeholder. {}",
            bundle.root, name, bundle.hint
        );
        // The absence is recorded rather than the build failed, so a checkout
        // without a network or a Node toolchain still produces a working agent.
        return format!(
            "/// The {name} files, absent because it was not built.\n\
             pub const {name}_BUNDLE: Option<&[(&str, &[u8])]> = None;\n\
             /// The newest modification time, when there is a bundle.\n\
             pub const {name}_MODIFIED: Option<u64> = None;\n\
             /// The request-path prefix this bundle is served under.\n\
             pub const {name}_PREFIX: &str = {prefix:?};\n"
        );
    };

    let newest = entries.iter().filter_map(|(_, modified)| *modified).max();
    let mut source = format!(
        "/// The {name} files, as request paths.\n\
         pub const {name}_BUNDLE: Option<&[(&str, &[u8])]> = Some(&[\n"
    );
    for (path, _) in &entries {
        // The absolute path is used for `include_bytes!`, because the macro
        // resolves relative to the file that contains it.
        let absolute = std::fs::canonicalize(root.join(path.trim_start_matches('/')))
            .unwrap_or_else(|_| root.join(path.trim_start_matches('/')));
        source.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            path,
            absolute.display().to_string()
        ));
    }
    source.push_str("]);\n");
    source.push_str(&format!(
        "/// The newest modification time in the bundle, in Unix seconds.\n\
         pub const {name}_MODIFIED: Option<u64> = Some({});\n",
        newest
            .and_then(|t| t.duration_since(SystemTime::UNIX_EPOCH).ok())
            .map(|d| d.as_secs())
            .unwrap_or(0)
    ));
    source.push_str(&format!(
        "/// The request-path prefix this bundle is served under.\n\
         pub const {name}_PREFIX: &str = {prefix:?};\n"
    ));
    source
}

/// Walks `root`, returning every file as a request path with its modification
/// time. `None` when the directory does not exist at all.
fn collect(root: &Path) -> Option<Vec<(String, Option<SystemTime>)>> {
    if !root.is_dir() {
        return None;
    }
    let mut out = Vec::new();
    walk(root, root, &mut out);
    Some(out)
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, Option<SystemTime>)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, out);
        } else {
            let Ok(relative) = path.strip_prefix(root) else {
                continue;
            };
            let request_path = format!("/{}", relative.display());
            let modified = entry.metadata().ok().and_then(|m| m.modified().ok());
            out.push((request_path, modified));
        }
    }
    // A stable order, so the generated file does not churn between builds and
    // invalidate the crate's own compilation for no reason.
    out.sort_by(|a, b| a.0.cmp(&b.0));
}
