//! The HTTP interface.

pub mod assets;

/// The embedded admin interface, generated by `build.rs`.
///
/// Included rather than written by hand because the file list depends on what is
/// on disk at compile time.
pub mod assets_bundle {
    include!(concat!(env!("OUT_DIR"), "/assets_bundle.rs"));
}
pub mod auth;
pub mod error;
pub mod routes;
pub mod server;
pub mod state;
pub mod upgrade;

pub use server::{HttpServer, ListenConfigSpec};
pub use state::AppState;
