//! The mihomo configuration field whitelist.
//!
//! **Generated file -- do not edit by hand.**
//!
//! Source: `MetaCubeX/mihomo` tag `v1.19.30`, file `config/config.go`.
//! Regenerate with `scripts/gen-config-whitelist.py` (see its docstring).
//!
//! # Why this exists
//!
//! `mihomo -t` accepts unknown fields without complaint, so a mistyped key
//! (`mixed-portt` for `mixed-port`) passes validation and the kernel then
//! falls back to its default. The config silently does not do what its author
//! wrote, which is the failure this list exists to catch.
//!
//! # Treating a miss as a warning, not a rejection
//!
//! Upstream adds fields over time. Rejecting an unknown key outright would
//! break a legitimate new config on an older agent, so this list is used to
//! *report* unknown keys. The caller decides whether that is fatal; see
//! `ConfigValidator::validate_semantic`.

/// The upstream tag this list was generated from.
pub const SOURCE_TAG: &str = "v1.19.30";

/// Top-level configuration keys.
pub const TOP_LEVEL: &[&str] = &[
    "port",
    "socks-port",
    "redir-port",
    "tproxy-port",
    "mixed-port",
    "ss-config",
    "vmess-config",
    "inbound-tfo",
    "inbound-mptcp",
    "authentication",
    "skip-auth-prefixes",
    "lan-allowed-ips",
    "lan-disallowed-ips",
    "allow-lan",
    "bind-address",
    "mode",
    "unified-delay",
    "log-level",
    "ipv6",
    "external-controller",
    "external-controller-routing-mark",
    "external-controller-pipe",
    "external-controller-unix",
    "external-controller-tls",
    "external-controller-cors",
    "external-ui",
    "external-ui-url",
    "external-ui-name",
    "external-doh-server",
    "secret",
    "interface-name",
    "routing-mark",
    "tunnels",
    "geo-auto-update",
    "geo-update-interval",
    "geodata-mode",
    "geodata-loader",
    "geosite-matcher",
    "tcp-concurrent",
    "find-process-mode",
    "global-client-fingerprint",
    "global-ua",
    "etag-support",
    "keep-alive-idle",
    "keep-alive-interval",
    "disable-keep-alive",
    "proxy-providers",
    "rule-providers",
    "proxies",
    "proxy-groups",
    "rules",
    "sub-rules",
    "listeners",
    "hosts",
    "dns",
    "ntp",
    "tun",
    "tuic-server",
    "iptables",
    "experimental",
    "profile",
    "geox-url",
    "sniffer",
    "tls",
    "clash-for-android",
];

/// Keys checked within a nested section.
pub const SECTIONS: &[(&str, &[&str])] = &[
    (
        "dns",
        &[
            "enable",
            "prefer-h3",
            "ipv6",
            "ipv6-timeout",
            "use-hosts",
            "use-system-hosts",
            "respect-rules",
            "nameserver",
            "fallback",
            "fallback-filter",
            "fallback-lazy-query",
            "listen",
            "listen-routing-mark",
            "enhanced-mode",
            "fake-ip-range",
            "fake-ip-range6",
            "fake-ip-filter",
            "fake-ip-filter-mode",
            "fake-ip-ttl",
            "default-nameserver",
            "cache-algorithm",
            "cache-max-size",
            "nameserver-policy",
            "proxy-server-nameserver",
            "proxy-server-nameserver-policy",
            "direct-nameserver",
            "direct-nameserver-follow-policy",
        ],
    ),
    (
        "tun",
        &[
            "enable",
            "device",
            "stack",
            "dns-hijack",
            "auto-route",
            "auto-detect-interface",
            "mtu",
            "gso",
            "gso-max-size",
            "inet4-address",
            "inet6-address",
            "iproute2-table-index",
            "iproute2-rule-index",
            "auto-redirect",
            "auto-redirect-input-mark",
            "auto-redirect-output-mark",
            "auto-redirect-iproute2-fallback-rule-index",
            "loopback-address",
            "strict-route",
            "route-address",
            "route-address-set",
            "route-exclude-address",
            "route-exclude-address-set",
            "include-interface",
            "exclude-interface",
            "include-uid",
            "include-uid-range",
            "exclude-uid",
            "exclude-uid-range",
            "exclude-src-port",
            "exclude-src-port-range",
            "exclude-dst-port",
            "exclude-dst-port-range",
            "include-android-user",
            "include-package",
            "exclude-package",
            "include-mac-address",
            "exclude-mac-address",
            "endpoint-independent-nat",
            "udp-timeout",
            "icmp-timeout",
            "disable-icmp-forwarding",
            "file-descriptor",
            "inet4-route-address",
            "inet6-route-address",
            "inet4-route-exclude-address",
            "inet6-route-exclude-address",
            "recvmsgx",
            "sendmsgx",
        ],
    ),
    (
        "ntp",
        &[
            "enable",
            "server",
            "port",
            "interval",
            "dialer-proxy",
            "write-to-system",
        ],
    ),
    (
        "sniffer",
        &[
            "enable",
            "override-destination",
            "sniffing",
            "force-domain",
            "skip-src-address",
            "skip-dst-address",
            "skip-domain",
            "port-whitelist",
            "force-dns-mapping",
            "parse-pure-ip",
            "sniff",
        ],
    ),
    (
        "experimental",
        &[
            "fingerprints",
            "quic-go-disable-gso",
            "quic-go-disable-ecn",
            "dialer-ip4p-convert",
        ],
    ),
    ("profile", &["store-selected", "store-fake-ip"]),
    (
        "tls",
        &[
            "certificate",
            "private-key",
            "client-auth-type",
            "client-auth-cert",
            "ech-key",
            "custom-certifactes",
        ],
    ),
    (
        "external-controller-cors",
        &["allow-origins", "allow-private-network"],
    ),
    ("geox-url", &["geoip", "mmdb", "asn", "geosite"]),
    (
        "iptables",
        &["enable", "inbound-interface", "bypass", "dns-redirect"],
    ),
    (
        "tuic-server",
        &[
            "enable",
            "listen",
            "token",
            "users",
            "certificate",
            "private-key",
            "congestion-controller",
            "max-idle-time",
            "authentication-timeout",
            "alpn",
            "max-udp-relay-packet-size",
            "cwnd",
        ],
    ),
];
